version: '3'

tasks:
  dev:
    desc: Run client in watch mode (requires server also running)
    cmds:
    - npx vite --host

  build:
    desc: Build production bundle
    cmds:
      - npx tsc --build
      - npx vite build

  check:
    desc: Check for errors
    cmds:
      - task: eslint
        vars:
          ESLINT_ARGS: ""
      - task: prettier
        vars:
          PRETTIER_ARGS: --check

  fix:
    desc: Fix errors
    cmds:
      - task: prettier
        vars:
          PRETTIER_ARGS: --write
      - task: eslint
        vars: 
          ESLINT_ARGS: --fix

  eslint:
    cmds:
      - npx eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0 --cache {{.ESLINT_ARGS}}

  prettier:
    cmds:
      - npx prettier "./**/*.{mts,ts,tsx,json,js,jsx,cjs,mjs,css,html}" {{.PRETTIER_ARGS}}
