name: Build
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - uses: Swatinem/rust-cache@v2
    - run: npm ci
    - run: task build:client --output group
    - uses: actions/upload-artifact@v4
      with:
        path: target/frontend
        name: app
        retention-days: 3

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: musl-tools
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-musl
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --bin start --release --target x86_64-unknown-linux-musl
    - uses: actions/upload-artifact@v4
      with:
        path: target/x86_64-unknown-linux-musl/release/start
        name: bin
        retention-days: 3
